name: Validar Rama de Origen para Main

on:
  pull_request:
    branches:
      - main
    types: [opened, edited, synchronized]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar si la rama de origen es stg
        run: |
          # Usamos la ruta completa del evento de PR para asegurar la lectura de la rama origen
          ORIGIN_BRANCH="${{ github.event.pull_request.head.ref }}"
          
          echo "Intentando fusionar desde: $ORIGIN_BRANCH hacia main"
          
          if [ "$ORIGIN_BRANCH" != "stg" ]; then
            echo "❌ ERROR: Solo se permiten Pull Requests hacia 'main' desde la rama 'stg'."
            echo "Tu rama de origen intentada fue: '$ORIGIN_BRANCH'."
            exit 1
          else
            echo "✅ Validación exitosa. La rama de origen es stg."
          fi